{% set version = "0.14.0" %}

package:
  name: input4mips-validation-suite
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/i/input4mips-validation/input4mips_validation-{{ version }}.tar.gz
    sha256: 32271582dbc1d8bf844c290a41d645daad59070fae245e07394c70373d2c4ae2

# Learning from matplotlib for the skips etc. here
# https://github.com/conda-forge/matplotlib-feedstock/blob/main/recipe/meta.yaml
build:
  number: 0

requirements:
  host:
    - python

outputs:
  - name: input4mips-validation
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - input4mips-validation = input4mips_validation.cli:app

    requirements:
      host:
        - python >=3.9
        - pip
        - pdm-backend

      run:
        - python >=3.9
        - iris >=3.0
        - netcdf4
        - numpy >=1.24, <2.0
        - cfchecker
        - cftime
        - attrs
        - cattrs
        - cf_xarray
        - loguru
        - ncdata
        - pandas
        - pint
        - pint-xarray
        - pooch
        - tqdm
        - typer
        - typing_extensions
        - validators
        - xarray

    test:
      imports:
        - input4mips_validation
      commands:
        - pip check
        - input4mips-validation --help
        - input4mips-validation db add-tree --help
        - input4mips-validation db create --help
        - input4mips-validation db validate --help
        - input4mips-validation upload-ftp --help
        - input4mips-validation validate-file --help
        - input4mips-validation validate-tree --help
      requires:
        - pip

  # A locked version, which will help avoid installation headaches
  # (e.g. dependency updates with breaking changes)
  # for those who just want the CLI.
  - name: input4mips-validation-locked
    build:
      noarch: python

    requirements:
      host:
        - python
        - pip
        - pdm-backend

      run:
        - python
        - {{ pin_subpackage('input4mips-validation', exact=True) }}
        - {{ pin_compatible('iris', lower_bound='3.8.1', upper_bound='3.8.2') }}
        - {{ pin_compatible('netcdf4', lower_bound='1.7.1', upper_bound='1.7.2') }}
        - {{ pin_compatible('numpy', lower_bound='1.26.4', upper_bound='1.26.5') }}
        - {{ pin_compatible('cfchecker', lower_bound='4.1.0', upper_bound='4.1.1') }}
        - {{ pin_compatible('cftime', lower_bound='1.6.4', upper_bound='1.6.5') }}
        - {{ pin_compatible('attrs', lower_bound='24.2.0', upper_bound='24.2.1') }}
        - {{ pin_compatible('cattrs', lower_bound='24.1.2', upper_bound='24.1.3') }}
        - {{ pin_compatible('cf_xarray', lower_bound='0.9.4', upper_bound='0.9.5') }}
        - {{ pin_compatible('loguru', lower_bound='0.7.2', upper_bound='0.7.3') }}
        - {{ pin_compatible('ncdata', lower_bound='0.1.1', upper_bound='0.1.2') }}
        - {{ pin_compatible('pandas', lower_bound='2.2.3', upper_bound='2.2.4') }}
        - {{ pin_compatible('pint', lower_bound='0.24.3', upper_bound='0.24.4') }}
        - {{ pin_compatible('pint-xarray', lower_bound='0.4', upper_bound='0.4.1') }}
        - {{ pin_compatible('pooch', lower_bound='1.8.2', upper_bound='1.8.3') }}
        - {{ pin_compatible('tqdm', lower_bound='4.66.5', upper_bound='4.66.6') }}
        - {{ pin_compatible('typer', lower_bound='0.12.5', upper_bound='0.12.6') }}
        - {{ pin_compatible('typing_extensions', lower_bound='4.12.2', upper_bound='4.12.3') }}
        - {{ pin_compatible('validators', lower_bound='0.34.0', upper_bound='0.34.1') }}
        - {{ pin_compatible('xarray', lower_bound='2024.7.0', upper_bound='2024.7.1') }}

    test:
      imports:
        - input4mips_validation
      commands:
        - pip check
        - input4mips-validation --help
        - input4mips-validation db add-tree --help
        - input4mips-validation db create --help
        - input4mips-validation db validate --help
        - input4mips-validation upload-ftp --help
        - input4mips-validation validate-file --help
        - input4mips-validation validate-tree --help
      requires:
        - pip

about:
  home: https://input4mips-validation.readthedocs.io
  summary: Validation of input4MIPs data (checking file formats, metadata etc.).
  description: |
    Input4MIPs validation is a validation library,
    specifically focussed on input4MIPs data (https://pcmdi.llnl.gov/mips/input4MIPs/).
    It is provided, by default, as a library.
    If you wish to use it as an application,
    we recommend installing the locked version of the package,
    i.e. `input4mips-validation-locked`,
    because this pins the versions of key dependencies
    (which avoids breakages because of updates to dependencies).
  license: BSD-3-Clause
  license_file: LICENCE
  doc_url: https://input4mips-validation.readthedocs.io
  dev_url: https://github.com/climate-resource/input4mips_validation

extra:
  feedstock-name: input4mips-validation
  recipe-maintainers:
    - znichollscr
