{% set version = "0.12.0" %}

package:
  name: input4mips-validation-suite
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/i/input4mips-validation/input4mips_validation-{{ version }}.tar.gz
    sha256: d777f040cf258ab13eac90a12ce234fbbe68971d709825b28249b3433b20a193

# Learning from matplotlib for the skips etc. here
# https://github.com/conda-forge/matplotlib-feedstock/blob/main/recipe/meta.yaml
build:
  number: 0

requirements:
  host:
    - python

outputs:
  - name: input4mips-validation
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - input4mips-validation = input4mips_validation.cli:app

    requirements:
      host:
        - python >=3.9
        - pip
        - pdm-backend

      run:
        - python >=3.9
        - iris >=3.0
        - netcdf4
        - numpy >=1.24, <2.0
        - cfchecker
        - cftime
        - attrs
        - cattrs
        - cf_xarray
        - loguru
        - ncdata
        - pandas
        - pint
        - pint-xarray
        - pooch
        - tqdm
        - typer
        - typing_extensions
        - validators
        - xarray


    test:
      imports:
        - input4mips_validation
      commands:
        - pip check
        - input4mips-validation --help
        - input4mips-validation db add-tree --help
        - input4mips-validation db create --help
        - input4mips-validation db validate --help
        - input4mips-validation upload-ftp --help
        - input4mips-validation validate-file --help
        - input4mips-validation validate-tree --help
      requires:
        - pip

  # A locked version, which will help avoid installation headaches
  # (e.g. dependency updates with breaking changes)
  # for those who just want the CLI.
  - name: input4mips-validation-locked
    build:
      noarch: python

    requirements:
      host:
        - python
        - pip
        - pdm-backend

      run:
        - python
        - {{ pin_subpackage('input4mips-validation', exact=True) }}
        - {{ pin_compatible('iris', min_pin='3.8.1', max_pin='3.8.2') }}
        - {{ pin_compatible('netcdf4', min_pin='1.7.1', max_pin='1.7.2') }}
        - {{ pin_compatible('numpy', min_pin='1.26.4', max_pin='1.26.5') }}
        - {{ pin_compatible('cfchecker', min_pin='4.1.0', max_pin='4.1.1') }}
        - {{ pin_compatible('cftime', min_pin='1.6.4', max_pin='1.6.5') }}
        - {{ pin_compatible('attrs', min_pin='23.2.0', max_pin='23.2.1') }}
        - {{ pin_compatible('cattrs', min_pin='23.2.3', max_pin='23.2.4') }}
        - {{ pin_compatible('cf_xarray', min_pin='0.9.4', max_pin='0.9.5') }}
        - {{ pin_compatible('loguru', min_pin='0.7.2', max_pin='0.7.3') }}
        - {{ pin_compatible('ncdata', min_pin='0.1.1', max_pin='0.1.2') }}
        - {{ pin_compatible('pandas', min_pin='2.2.2', max_pin='2.2.3') }}
        - {{ pin_compatible('pint', min_pin='0.24.3', max_pin='0.24.4') }}
        - {{ pin_compatible('pint-xarray', min_pin='0.4', max_pin='0.4.1') }}
        - {{ pin_compatible('pooch', min_pin='1.8.2', max_pin='1.8.3') }}
        - {{ pin_compatible('tqdm', min_pin='4.66.4', max_pin='4.66.5') }}
        - {{ pin_compatible('typer', min_pin='0.12.3', max_pin='0.12.4') }}
        - {{ pin_compatible('typing_extensions', min_pin='4.12.2', max_pin='4.12.3') }}
        - {{ pin_compatible('validators', min_pin='0.33.0', max_pin='0.33.1') }}
        - {{ pin_compatible('xarray', min_pin='2024.6.0', max_pin='2024.6.1') }}

    test:
      imports:
        - input4mips_validation
      commands:
        - pip check
        - input4mips-validation --help
        - input4mips-validation db add-tree --help
        - input4mips-validation db create --help
        - input4mips-validation db validate --help
        - input4mips-validation upload-ftp --help
        - input4mips-validation validate-file --help
        - input4mips-validation validate-tree --help
      requires:
        - pip

about:
  home: https://input4mips-validation.readthedocs.io
  summary: Validation of input4MIPs data (checking file formats, metadata etc.).
  description: |
    Input4MIPs validation is a validation library,
    specifically focussed on input4MIPs data (https://pcmdi.llnl.gov/mips/input4MIPs/).
    It is provided, by default, as a library.
    If you wish to use it as an application,
    we recommend installing the locked version of the package,
    i.e. `input4mips-validation-locked`,
    because this pins the versions of key dependencies
    (which avoids breakages because of updates to dependencies).
  license: BSD-3-Clause
  license_file: LICENCE
  doc_url: https://input4mips-validation.readthedocs.io
  dev_url: https://github.com/climate-resource/input4mips_validation

extra:
  feedstock-name: input4mips-validation
  recipe-maintainers:
    - znichollscr
